CREATE TABLE IF NOT EXISTS events (
	id UUID PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	location VARCHAR(255) NOT NULL,
	start_at TIMESTAMPTZ NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)