CREATE TABLE IF NOT EXISTS dojos (
	id UUID PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	logo_url TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE users
	ADD COLUMN IF NOT EXISTS password_hash TEXT NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS role VARCHAR(32) NOT NULL DEFAULT 'super_admin',
	ADD COLUMN IF NOT EXISTS dojo_id UUID NULL REFERENCES dojos(id) ON DELETE SET NULL,
	ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
	ADD COLUMN IF NOT EXISTS last_login TIMESTAMPTZ NULL,
	ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT FALSE,
	ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ NULL,
	ADD COLUMN IF NOT EXISTS reset_token TEXT NULL,
	ADD COLUMN IF NOT EXISTS reset_token_expiry TIMESTAMPTZ NULL,
	ADD COLUMN IF NOT EXISTS created_by UUID NULL REFERENCES users(id) ON DELETE SET NULL,
	ADD COLUMN IF NOT EXISTS updated_by UUID NULL REFERENCES users(id) ON DELETE SET NULL;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'users_role_check'
	) THEN
		ALTER TABLE users
			ADD CONSTRAINT users_role_check CHECK (role IN ('super_admin', 'dojo_admin'));
	END IF;
END $$;

CREATE INDEX IF NOT EXISTS dojos_created_at_id_idx ON dojos(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS users_created_at_id_idx ON users(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS users_dojo_id_idx ON users(dojo_id);
