export const ROUTES = Object.freeze({
  home: "/",
  auth: "/auth",
  dashboardDojo: "/dashboard/dojo",
  dashboardDojoEvent: (eventId) => `/dashboard/dojo/events/${eventId}`,
  dashboardDojoEventRegister: (eventId) => `/dashboard/dojo/events/${eventId}/register`,
  users: "/users",
  usersCreate: "/users/create",
  usersDetail: (id) => `/users/${id}`,
  usersEdit: (id) => `/users/${id}/edit`,
  dojos: "/dojos",
  dojosCreate: "/dojos/create",
  dojosDetail: (id) => `/dojos/${id}`,
  dojosEdit: (id) => `/dojos/${id}/edit`,
  events: "/events",
  eventsCreate: "/events/create",
  eventsDetail: (id) => `/events/${id}`,
  eventsEdit: (id) => `/events/${id}/edit`,
});