export const ROUTES = Object.freeze({
  home: "/",
  auth: "/auth",
  dashboardDojo: "/dashboard/dojo",
  dashboardDojoEvent: (eventId) => `/dashboard/dojo/events/${eventId}`,
  dashboardDojoEventRegister: (eventId) => `/dashboard/dojo/events/${eventId}/register`,
  users: "/users",
  usersCreate: "/users/create",
  usersDetail: (id) => `/users/${id}`,
  usersEdit: (id) => `/users/${id}/edit`,
  dojos: "/dojos",
  dojosCreate: "/dojos/create",
  dojosDetail: (id) => `/dojos/${id}`,
  dojosEdit: (id) => `/dojos/${id}/edit`,
  events: "/events",
  eventsCreate: "/events/create",
  eventsDetail: (id) => `/events/${id}`,
  eventsRegistrationDojoDetail: (eventId, dojoId) => `/events/${eventId}/registrations/${dojoId}`,
  eventsRegistrationDojoPaymentProof: (eventId, dojoId) => `/events/${eventId}/registrations/${dojoId}/payment-proof`,
  eventsEdit: (id) => `/events/${id}/edit`,
  kelasTanding: "/kelas-tanding",
  kelasTandingCreate: "/kelas-tanding/create",
  kelasTandingDetail: (id) => `/kelas-tanding/${id}`,
  kelasTandingEdit: (id) => `/kelas-tanding/${id}/edit`,
});
